name: Run code linting and tests

on:
  pull_request:
    branches:
    - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        context:
        # - comprima-adapter TODO: Enable when there are tests.
        - reading-room-frontend
        # - reading-room-search TODO: Enable when there are tests.

    steps:
    - name: ğŸ›ï¸ Checkout
      uses: actions/checkout@v3

    - name: ğŸ”§ Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: ğŸ’¾ NPM Install ${{ matrix.context }}
      uses: bahmutov/npm-install@v1
      with:
        working-directory: ./packages/${{ matrix.context }}

    - name: ğŸ” Lint ${{ matrix.context }}
      run: |
        cd ./packages/${{ matrix.context }}
        npm run lint

    - name: ğŸ¤– Test ${{ matrix.context }}
      run: |
        cd ./packages/${{ matrix.context }}
        npm run test
