name: Run code linting and tests

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    strategy:
      matrix:
        context:
          - comprima-adapter
          - comprima-crawler
          - comprima-ocr
          - reading-room-frontend
          - reading-room-search

    steps:
      - name: ğŸ›ï¸ Checkout
        uses: actions/checkout@v4

      - name: ğŸ”§ Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      #- name: ğŸ’¾ PNPM Install ${{ matrix.context }}
      #  uses: ./.github/actions/pnpm-setup
      #  with:
      #    working-directory: ./packages/${{ matrix.context }}

      - name: Install PNPM
        uses: pnpm/action-setup@v4

      - name: ğŸ’¾ PNPM Install ${{ matrix.context }}
        run: pnpm install
        with:
          working-directory: ./packages/${{ matrix.context }}
      #      - name: ğŸ’¾ NPM Install ${{ matrix.context }}
      #        uses: bahmutov/npm-install@v1
      #        with:
      #          working-directory: ./packages/${{ matrix.context }}

      - name: ğŸ” Lint ${{ matrix.context }}
        run: |
          cd ./packages/${{ matrix.context }}
          pnpm run lint

      - name: ğŸ¤– Test ${{ matrix.context }}
        run: |
          cd ./packages/${{ matrix.context }}
          pnpm run test
